- hosts: localhost
  become: true
  tasks:
  
  - name: Update and upgrade
    apt:
      name: "*"
      state: latest
      force_apt_get: yes

  - name: Install packages
    apt:
      name:
      - git
      - vim
      - ntfs-3g
      state: present

  - name: Mount USB Drive
    mount:
      path: /mnt/5TERA
      src: /dev/sda2
      fstype: ntfs
      state: mounted

  - name: Install VimRC
    git:
      repo: https://github.com/amix/vimrc.git
      dest: ~/.vim_runtime
      depth: 1

  - name: Install VimRC
    shell: sh ~/.vim_runtime/install_awesome_vimrc.sh


