- hosts: localhost
  tasks:

  - name: Download pip
    get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: /tmp/get-pip.py
  
  - name: Install pip
    command: python /tmp/get-pip.py

  - name: Upgrade pip
    pip:
      name: pip
      state: latest
   
  - name: Install Docker Python Module
    pip:
      name: docker
